# """
# Django settings for stock project.

# Generated by 'django-admin startproject' using Django 5.1.

# For more information on this file, see
# https://docs.djangoproject.com/en/5.1/topics/settings/

# For the full list of settings and their values, see
# https://docs.djangoproject.com/en/5.1/ref/settings/
# """

# from pathlib import Path

# # Build paths inside the project like this: BASE_DIR / 'subdir'.
# BASE_DIR = Path(__file__).resolve().parent.parent


# # Quick-start development settings - unsuitable for production
# # See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# # SECURITY WARNING: keep the secret key used in production secret!
# SECRET_KEY = 'django-insecure-fxf$tynj3apu2lz)-5iy+ktgoc)wb%n6#uu4ait#ubiy&-5tt8'

# # SECURITY WARNING: don't run with debug turned on in production!
# DEBUG = True

# ALLOWED_HOSTS = []


# # Application definition

# INSTALLED_APPS = [
#     'django.contrib.admin',
#     'django.contrib.auth',
#     'django.contrib.contenttypes',
#     'django.contrib.sessions',
#     'django.contrib.messages',
#     'django.contrib.staticfiles',


# MIDDLEWARE = [
#     'django.middleware.security.SecurityMiddleware',
#     'django.contrib.sessions.middleware.SessionMiddleware',
#     'django.middleware.common.CommonMiddleware',
#     'django.middleware.csrf.CsrfViewMiddleware',
#     'django.contrib.auth.middleware.AuthenticationMiddleware',
#     'django.contrib.messages.middleware.MessageMiddleware',
#     'django.middleware.clickjacking.XFrameOptionsMiddleware',
# ]

# ROOT_URLCONF = 'stock.urls'

# TEMPLATES = [
#     {
#         'BACKEND': 'django.template.backends.django.DjangoTemplates',
#         'DIRS': [],
#         'APP_DIRS': True,
#         'OPTIONS': {
#             'context_processors': [
#                 'django.template.context_processors.debug',
#                 'django.template.context_processors.request',
#                 'django.contrib.auth.context_processors.auth',
#                 'django.contrib.messages.context_processors.messages',
#             ],
#         },
#     },
# ]

# WSGI_APPLICATION = 'stock.wsgi.application'


# # Database
# # https://docs.djangoproject.com/en/5.1/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }


# # Password validation
# # https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

# AUTH_PASSWORD_VALIDATORS = [
#     {
#         'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
#     },
#     {
#         'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
#     },
#     {
#         'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
#     },
#     {
#         'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
#     },
# ]


# # Internationalization
# # https://docs.djangoproject.com/en/5.1/topics/i18n/

# LANGUAGE_CODE = 'en-us'

# TIME_ZONE = 'UTC'

# USE_I18N = True

# USE_TZ = True


# # Static files (CSS, JavaScript, Images)
# # https://docs.djangoproject.com/en/5.1/howto/static-files/

# STATIC_URL = 'static/'

# # Default primary key field type
# # https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

# DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'



"""
Django settings for stock project.
"""
import os  # accès aux variables d'environnement et chemins
from pathlib import Path  # manipulation de chemins OS-agnostiques
from dotenv import load_dotenv  # chargement des variables depuis .env

load_dotenv()  # charge les variables d'environnement depuis un fichier .env si présent

# Chemin de base du projet (deux niveaux au-dessus de ce fichier)
BASE_DIR = Path(__file__).resolve().parent.parent

# Clé secrète de Django — ne pas exposer en production
# Ici elle est en clair pour le développement; utiliser une variable d'environnement
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-fxf$tynj3apu2lz)-5iy+ktgoc)wb%n6#uu4ait#ubiy&-5tt8')

# Mode DEBUG (True = information détaillée, à désactiver en production)
DEBUG = True

# Hôtes autorisés (mettre la/les domain(es) en production)
ALLOWED_HOSTS = []

# Applications installées
# - apps Django par défaut
# - bibliothèques tierces utilisées par le projet
# - applications locales du projet
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Bibliothèques tierces
    'django_bootstrap5',
    'crispy_forms',
    'crispy_bootstrap5',
    'import_export',
    'qr_code',

    # Application locale principale
    'gestion_stock',
]

# Configuration Crispy Forms (pack Bootstrap5)
CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"

# Middleware : couche par couche gérée par Django
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# Module racine des URLs pour le projet
ROOT_URLCONF = 'stock.urls'

# Configuration des templates Django
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        # Dossier global de templates à la racine du projet
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,  # recherche automatique dans les dossiers templates des apps
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                # context processor local pour notifications/alertes
                'gestion_stock.context_processors.notification_context',
            ],
        },
    },
]

# Application WSGI
WSGI_APPLICATION = 'stock.wsgi.application'

# Base de données : configuration par défaut SQLite pour le développement

DATABASES = {
    'default': {
        'ENGINE': 'mssql',
        'NAME': 'GestionStock',
        'USER': 'sa',
        'PASSWORD': 'Masitan1',
        'HOST': r'localhost\SQLEXPRESS',
        'PORT': '',
        'OPTIONS': {
            'driver': 'ODBC Driver 17 for SQL Server',
            'trusted_connection': 'yes',
        },
    }
}


# Validators de mot de passe fournis par Django (recommandés en production)
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalisation : langue et fuseau horaire
LANGUAGE_CODE = 'fr-fr'  # interface en français
TIME_ZONE = 'Africa/Abidjan'  # réglage du fuseau horaire
USE_I18N = True  # activer la traduction
USE_TZ = True  # activer la gestion des timezones

# Fichiers statiques (CSS, JS, images)
STATIC_URL = 'static/'
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]  # dossier des assets en dev
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')  # dossier collectstatic en prod

# Fichiers média (uploads utilisateur)
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Type de clé primaire par défaut pour les modèles
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Répétition de la config Crispy (sécurise le pack utilisé)
CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"

# URLs de redirection après authentification
LOGIN_URL = 'login'  # nom de la vue de connexion
LOGIN_REDIRECT_URL = 'dashboard'  # où rediriger après login
LOGOUT_REDIRECT_URL = 'login'  # où rediriger après logout

# Session : durée et comportement à la fermeture du navigateur
SESSION_COOKIE_AGE = 3600  # durée de session en secondes (1 heure)
SESSION_EXPIRE_AT_BROWSER_CLOSE = True  # expire à la fermeture du navigateur

# ---- Configuration Email (SMTP via .env) ----
EMAIL_BACKEND    = os.getenv('EMAIL_BACKEND', 'django.core.mail.backends.smtp.EmailBackend')
EMAIL_HOST       = os.getenv('EMAIL_HOST', 'smtp.gmail.com')
EMAIL_PORT       = int(os.getenv('EMAIL_PORT', 587))
EMAIL_USE_TLS    = os.getenv('EMAIL_USE_TLS', 'True') == 'True'
EMAIL_HOST_USER  = os.getenv('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', '')
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', 'StockMaster Pro <no-reply@stockmaster.com>')

# Adresses e-mail des administrateurs pour les alertes automatiques
ADMIN_EMAILS = [e.strip() for e in os.getenv('ADMIN_EMAILS', '').split(',') if e.strip()]