# Generated by Django 5.1 on 2026-01-02 20:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_article', models.CharField(max_length=50, unique=True, verbose_name='Code article')),
                ('code_barre', models.CharField(blank=True, max_length=100, unique=True, verbose_name='Code-barres')),
                ('designation', models.CharField(max_length=200)),
                ('prix_achat', models.DecimalField(decimal_places=2, max_digits=10)),
                ('prix_vente', models.DecimalField(decimal_places=2, max_digits=10)),
                ('seuil_alerte', models.IntegerField(default=10)),
                ('unite', models.CharField(choices=[('unite', 'Unité'), ('kg', 'Kilogramme'), ('litre', 'Litre'), ('paquet', 'Paquet'), ('carton', 'Carton')], default='unite', max_length=20)),
                ('emplacement', models.CharField(blank=True, help_text='Rayon/Étagère', max_length=50)),
                ('date_peremption', models.DateField(blank=True, null=True, verbose_name='Date de péremption')),
                ('actif', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
            },
        ),
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Catégorie',
                'verbose_name_plural': 'Catégories',
            },
        ),
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('nom', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=100)),
                ('telephone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('adresse', models.TextField(blank=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Alerte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_alerte', models.CharField(choices=[('stock_faible', 'Stock faible'), ('peremption', 'Péremption proche'), ('rupture', 'Rupture de stock'), ('autre', 'Autre')], max_length=20)),
                ('message', models.TextField()),
                ('priorite', models.IntegerField(choices=[(1, 'Basse'), (2, 'Moyenne'), (3, 'Haute')], default=1)),
                ('lu', models.BooleanField(default=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_lu', models.DateTimeField(blank=True, null=True)),
                ('article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion_stock.article')),
            ],
            options={
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='AjustementStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite_reelle', models.IntegerField()),
                ('quantite_systeme', models.IntegerField()),
                ('difference', models.IntegerField()),
                ('raison', models.CharField(choices=[('inventaire', 'Inventaire'), ('casse', 'Casse'), ('vol', 'Vol'), ('erreur', 'Erreur de saisie'), ('autre', 'Autre')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('date_ajustement', models.DateTimeField(auto_now_add=True)),
                ('utilisateur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_stock.article')),
            ],
            options={
                'verbose_name': 'Ajustement de stock',
                'verbose_name_plural': 'Ajustements de stock',
            },
        ),
        migrations.AddField(
            model_name='article',
            name='categorie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion_stock.categorie'),
        ),
        migrations.CreateModel(
            name='CommandeFournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=50, unique=True)),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('envoyee', 'Envoyée'), ('recue', 'Reçue'), ('annulee', 'Annulée')], default='brouillon', max_length=20)),
                ('date_commande', models.DateField(auto_now_add=True)),
                ('date_reception', models.DateField(blank=True, null=True)),
                ('montant_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('notes', models.TextField(blank=True)),
                ('utilisateur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_stock.fournisseur')),
            ],
            options={
                'verbose_name': 'Commande fournisseur',
                'verbose_name_plural': 'Commandes fournisseur',
            },
        ),
        migrations.AddField(
            model_name='article',
            name='fournisseur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion_stock.fournisseur'),
        ),
        migrations.CreateModel(
            name='LigneCommande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.IntegerField()),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_stock.article')),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='gestion_stock.commandefournisseur')),
            ],
            options={
                'verbose_name': 'Ligne de commande',
                'verbose_name_plural': 'Lignes de commande',
            },
        ),
        migrations.CreateModel(
            name='MouvementStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_mouvement', models.CharField(choices=[('entree', 'Entrée'), ('sortie', 'Sortie'), ('inventaire', 'Inventaire'), ('ajustement', 'Ajustement'), ('retour', 'Retour')], max_length=20)),
                ('quantite', models.IntegerField()),
                ('quantite_avant', models.IntegerField()),
                ('quantite_apres', models.IntegerField()),
                ('motif', models.TextField(blank=True)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('date_mouvement', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_stock.article')),
                ('utilisateur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mouvement de stock',
                'verbose_name_plural': 'Mouvements de stock',
            },
        ),
        migrations.CreateModel(
            name='ProfilUtilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Administrateur'), ('gestionnaire', 'Gestionnaire'), ('vendeur', 'Vendeur')], default='vendeur', max_length=20)),
                ('nom_complet', models.CharField(max_length=100)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('date_embauche', models.DateField(auto_now_add=True)),
                ('actif', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.IntegerField(default=0)),
                ('quantite_min', models.IntegerField(default=0)),
                ('quantite_max', models.IntegerField(default=1000)),
                ('emplacement', models.CharField(max_length=100)),
                ('date_derniere_entree', models.DateTimeField(blank=True, null=True)),
                ('date_derniere_sortie', models.DateTimeField(blank=True, null=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_stock.article')),
            ],
            options={
                'verbose_name': 'Stock',
                'verbose_name_plural': 'Stocks',
            },
        ),
    ]
